format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$line_break\
$character"""

[directory]
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[nodejs]
format = "[$symbol($version)]($style) "
symbol = " "

[python]
format = "[$symbol($version)]($style) "
symbol = " "

[rust]
format = "[$symbol($version)]($style) "
symbol = " "

[golang]
format = "[$symbol($version)]($style) "
symbol = " "

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
